name: Development

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        
      - name: Build Image
        run: |
            cd debian-arm
            mkdir images
            for c in $(cat image.list); do docker pull $c && \
             docker save $_ > images/$(date +%s).tar; \
            done
            docker buildx build --platform linux/arm/v7 -o deb-arm --file Dockerfile .
                   
      - name: upload-debian
        uses: actions/upload-artifact@v1
        with:
          name: deb-arm
          path: debian-arm/deb-arm/selfextract.bsx
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
#  push:
#    # Ensure test job passes before pushing image.
#    needs: 
#    - test-rhel
#    - test-deb

#    runs-on: ubuntu-latest
#    if: github.event_name == 'push'

#    steps:
#      - uses: actions/checkout@v2

#      - name: Build image
        
#        run: docker build . --file Dockerfile --tag image
